services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment: 
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3307:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql
