services:  
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
    - POSTGRES_USER=test
    - POSTGRES_PASSWORD=password
    ports:
    - 5431:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
